#!/usr/bin/env python3
import json

# Read the file
with open('/Users/a195143/BitBucket/Compose/NamazVakitleri/prayer_settings/src/main/assets/cities.json', 'r') as f:
    data = json.load(f)

# Remove existing Turkey entries
data['cities'] = [c for c in data['cities'] if c['country'] != 'Turkey']

# Complete 81 Turkish provinces with districts grouped by city
turkish_cities = [
    # Istanbul - 39 districts
    # Avrupa Yakası (European Side)
    {"name": "Arnavutköy", "country": "Turkey", "latitude": 41.1827, "longitude": 28.3445, "timezone": "Europe/Istanbul", "county": "Avrupa Yakası", "city": "Istanbul"},
    {"name": "Avcılar", "country": "Turkey", "latitude": 40.9965, "longitude": 28.7157, "timezone": "Europe/Istanbul", "county": "Avrupa Yakası", "city": "Istanbul"},
    {"name": "Bağcılar", "country": "Turkey", "latitude": 41.0392, "longitude": 28.8526, "timezone": "Europe/Istanbul", "county": "Avrupa Yakası", "city": "Istanbul"},
    {"name": "Bahçelievler", "country": "Turkey", "latitude": 41.0034, "longitude": 28.8086, "timezone": "Europe/Istanbul", "county": "Avrupa Yakası", "city": "Istanbul"},
    {"name": "Bakırköy", "country": "Turkey", "latitude": 40.9746, "longitude": 28.7926, "timezone": "Europe/Istanbul", "county": "Avrupa Yakası", "city": "Istanbul"},
    {"name": "Başakşehir", "country": "Turkey", "latitude": 41.0897, "longitude": 28.8373, "timezone": "Europe/Istanbul", "county": "Avrupa Yakası", "city": "Istanbul"},
    {"name": "Bayrampaşa", "country": "Turkey", "latitude": 41.0470, "longitude": 28.9091, "timezone": "Europe/Istanbul", "county": "Avrupa Yakası", "city": "Istanbul"},
    {"name": "Beşiktaş", "country": "Turkey", "latitude": 41.0446, "longitude": 29.0072, "timezone": "Europe/Istanbul", "county": "Avrupa Yakası", "city": "Istanbul"},
    {"name": "Beylikdüzü", "country": "Turkey", "latitude": 41.0925, "longitude": 28.6360, "timezone": "Europe/Istanbul", "county": "Avrupa Yakası", "city": "Istanbul"},
    {"name": "Beyoğlu", "country": "Turkey", "latitude": 41.0341, "longitude": 28.9777, "timezone": "Europe/Istanbul", "county": "Avrupa Yakası", "city": "Istanbul"},
    {"name": "Büyükçekmece", "country": "Turkey", "latitude": 41.0209, "longitude": 28.5970, "timezone": "Europe/Istanbul", "county": "Avrupa Yakası", "city": "Istanbul"},
    {"name": "Çatalca", "country": "Turkey", "latitude": 41.1434, "longitude": 28.4673, "timezone": "Europe/Istanbul", "county": "Avrupa Yakası", "city": "Istanbul"},
    {"name": "Esenler", "country": "Turkey", "latitude": 41.0462, "longitude": 28.8821, "timezone": "Europe/Istanbul", "county": "Avrupa Yakası", "city": "Istanbul"},
    {"name": "Esenyurt", "country": "Turkey", "latitude": 41.0627, "longitude": 28.6276, "timezone": "Europe/Istanbul", "county": "Avrupa Yakası", "city": "Istanbul"},
    {"name": "Eyüpsultan", "country": "Turkey", "latitude": 41.0679, "longitude": 28.9403, "timezone": "Europe/Istanbul", "county": "Avrupa Yakası", "city": "Istanbul"},
    {"name": "Fatih", "country": "Turkey", "latitude": 41.0364, "longitude": 28.9603, "timezone": "Europe/Istanbul", "county": "Avrupa Yakası", "city": "Istanbul"},
    {"name": "Gaziosmanpaşa", "country": "Turkey", "latitude": 41.0581, "longitude": 28.9132, "timezone": "Europe/Istanbul", "county": "Avrupa Yakası", "city": "Istanbul"},
    {"name": "Güngören", "country": "Turkey", "latitude": 41.0215, "longitude": 28.8526, "timezone": "Europe/Istanbul", "county": "Avrupa Yakası", "city": "Istanbul"},
    {"name": "Kağıthane", "country": "Turkey", "latitude": 41.0724, "longitude": 28.9443, "timezone": "Europe/Istanbul", "county": "Avrupa Yakası", "city": "Istanbul"},
    {"name": "Küçükçekmece", "country": "Turkey", "latitude": 41.0449, "longitude": 28.7284, "timezone": "Europe/Istanbul", "county": "Avrupa Yakası", "city": "Istanbul"},
    {"name": "Sarıyer", "country": "Turkey", "latitude": 41.1659, "longitude": 29.0566, "timezone": "Europe/Istanbul", "county": "Avrupa Yakası", "city": "Istanbul"},
    {"name": "Silivri", "country": "Turkey", "latitude": 41.0735, "longitude": 28.2693, "timezone": "Europe/Istanbul", "county": "Avrupa Yakası", "city": "Istanbul"},
    {"name": "Sultangazi", "country": "Turkey", "latitude": 41.0799, "longitude": 28.8627, "timezone": "Europe/Istanbul", "county": "Avrupa Yakası", "city": "Istanbul"},
    {"name": "Şişli", "country": "Turkey", "latitude": 41.0610, "longitude": 28.9675, "timezone": "Europe/Istanbul", "county": "Avrupa Yakası", "city": "Istanbul"},
    {"name": "Zeytinburnu", "country": "Turkey", "latitude": 41.0184, "longitude": 28.8814, "timezone": "Europe/Istanbul", "county": "Avrupa Yakası", "city": "Istanbul"},
    
    # Anadolu Yakası (Asian Side)
    {"name": "Adalar", "country": "Turkey", "latitude": 40.8730, "longitude": 29.0100, "timezone": "Europe/Istanbul", "county": "Anadolu Yakası", "city": "Istanbul"},
    {"name": "Ataşehir", "country": "Turkey", "latitude": 40.9929, "longitude": 29.1032, "timezone": "Europe/Istanbul", "county": "Anadolu Yakası", "city": "Istanbul"},
    {"name": "Beykoz", "country": "Turkey", "latitude": 41.0678, "longitude": 29.1069, "timezone": "Europe/Istanbul", "county": "Anadolu Yakası", "city": "Istanbul"},
    {"name": "Çekmeköy", "country": "Turkey", "latitude": 41.0478, "longitude": 29.1798, "timezone": "Europe/Istanbul", "county": "Anadolu Yakası", "city": "Istanbul"},
    {"name": "Kadıköy", "country": "Turkey", "latitude": 40.9824, "longitude": 29.0727, "timezone": "Europe/Istanbul", "county": "Anadolu Yakası", "city": "Istanbul"},
    {"name": "Kartal", "country": "Turkey", "latitude": 40.9007, "longitude": 29.1745, "timezone": "Europe/Istanbul", "county": "Anadolu Yakası", "city": "Istanbul"},
    {"name": "Maltepe", "country": "Turkey", "latitude": 40.9365, "longitude": 29.0913, "timezone": "Europe/Istanbul", "county": "Anadolu Yakası", "city": "Istanbul"},
    {"name": "Pendik", "country": "Turkey", "latitude": 40.8782, "longitude": 29.2849, "timezone": "Europe/Istanbul", "county": "Anadolu Yakası", "city": "Istanbul"},
    {"name": "Sancaktepe", "country": "Turkey", "latitude": 41.0135, "longitude": 29.2130, "timezone": "Europe/Istanbul", "county": "Anadolu Yakası", "city": "Istanbul"},
    {"name": "Sultanbeyli", "country": "Turkey", "latitude": 40.9629, "longitude": 29.2603, "timezone": "Europe/Istanbul", "county": "Anadolu Yakası", "city": "Istanbul"},
    {"name": "Şile", "country": "Turkey", "latitude": 41.1807, "longitude": 29.6130, "timezone": "Europe/Istanbul", "county": "Anadolu Yakası", "city": "Istanbul"},
    {"name": "Tuzla", "country": "Turkey", "latitude": 40.8552, "longitude": 29.3144, "timezone": "Europe/Istanbul", "county": "Anadolu Yakası", "city": "Istanbul"},
    {"name": "Ümraniye", "country": "Turkey", "latitude": 41.0284, "longitude": 29.1020, "timezone": "Europe/Istanbul", "county": "Anadolu Yakası", "city": "Istanbul"},
    {"name": "Üsküdar", "country": "Turkey", "latitude": 41.0400, "longitude": 29.0285, "timezone": "Europe/Istanbul", "county": "Anadolu Yakası", "city": "Istanbul"},
    
    # Other 81 Turkish provinces
    {"name": "Aladağ", "country": "Turkey", "latitude": 37.5379, "longitude": 35.4009, "timezone": "Europe/Istanbul", "county": "Adana", "city": "Adana"},
    {"name": "Ceyhan", "country": "Turkey", "latitude": 37.0247, "longitude": 35.8251, "timezone": "Europe/Istanbul", "county": "Adana", "city": "Adana"},
    {"name": "Feke", "country": "Turkey", "latitude": 37.9429, "longitude": 35.8829, "timezone": "Europe/Istanbul", "county": "Adana", "city": "Adana"},
    {"name": "İmamoğlu", "country": "Turkey", "latitude": 37.2133, "longitude": 35.6014, "timezone": "Europe/Istanbul", "county": "Adana", "city": "Adana"},
    {"name": "Karaisalı", "country": "Turkey", "latitude": 37.2573, "longitude": 35.4799, "timezone": "Europe/Istanbul", "county": "Adana", "city": "Adana"},
    {"name": "Kozan", "country": "Turkey", "latitude": 37.4526, "longitude": 35.8163, "timezone": "Europe/Istanbul", "county": "Adana", "city": "Adana"},
    {"name": "Pozantı", "country": "Turkey", "latitude": 37.3255, "longitude": 34.8714, "timezone": "Europe/Istanbul", "county": "Adana", "city": "Adana"},
    {"name": "Seyhan", "country": "Turkey", "latitude": 36.9914, "longitude": 35.3308, "timezone": "Europe/Istanbul", "county": "Adana", "city": "Adana"},
    {"name": "Tufanbeyli", "country": "Turkey", "latitude": 38.1211, "longitude": 36.2172, "timezone": "Europe/Istanbul", "county": "Adana", "city": "Adana"},
    {"name": "Yumurtalık", "country": "Turkey", "latitude": 36.7595, "longitude": 35.7938, "timezone": "Europe/Istanbul", "county": "Adana", "city": "Adana"},
    
    {"name": "Ankara", "country": "Turkey", "latitude": 39.9334, "longitude": 32.8597, "timezone": "Europe/Istanbul", "county": "Ankara", "city": "Ankara"},
    {"name": "Çankaya", "country": "Turkey", "latitude": 39.9027, "longitude": 32.8594, "timezone": "Europe/Istanbul", "county": "Ankara", "city": "Ankara"},
    {"name": "Keçiören", "country": "Turkey", "latitude": 40.0128, "longitude": 32.8646, "timezone": "Europe/Istanbul", "county": "Ankara", "city": "Ankara"},
    {"name": "Sincan", "country": "Turkey", "latitude": 39.9776, "longitude": 32.5834, "timezone": "Europe/Istanbul", "county": "Ankara", "city": "Ankara"},
    {"name": "Etimesgut", "country": "Turkey", "latitude": 39.9466, "longitude": 32.6297, "timezone": "Europe/Istanbul", "county": "Ankara", "city": "Ankara"},
    {"name": "Yenimahalle", "country": "Turkey", "latitude": 39.9842, "longitude": 32.7075, "timezone": "Europe/Istanbul", "county": "Ankara", "city": "Ankara"},
    {"name": "Polatlı", "country": "Turkey", "latitude": 39.5794, "longitude": 32.1451, "timezone": "Europe/Istanbul", "county": "Ankara", "city": "Ankara"},
    {"name": "Çubuk", "country": "Turkey", "latitude": 40.0333, "longitude": 32.8917, "timezone": "Europe/Istanbul", "county": "Ankara", "city": "Ankara"},
    {"name": "Elmadağ", "country": "Turkey", "latitude": 39.9055, "longitude": 33.2295, "timezone": "Europe/Istanbul", "county": "Ankara", "city": "Ankara"},
    {"name": "Kalecik", "country": "Turkey", "latitude": 40.1245, "longitude": 33.4125, "timezone": "Europe/Istanbul", "county": "Ankara", "city": "Ankara"},
    
    {"name": "Buca", "country": "Turkey", "latitude": 38.4625, "longitude": 27.1527, "timezone": "Europe/Istanbul", "county": "Izmir", "city": "Izmir"},
    {"name": "Karşıyaka", "country": "Turkey", "latitude": 38.4622, "longitude": 27.0963, "timezone": "Europe/Istanbul", "county": "Izmir", "city": "Izmir"},
    {"name": "Konak", "country": "Turkey", "latitude": 38.4237, "longitude": 27.1428, "timezone": "Europe/Istanbul", "county": "Izmir", "city": "Izmir"},
    {"name": "Bornova", "country": "Turkey", "latitude": 38.4792, "longitude": 27.2557, "timezone": "Europe/Istanbul", "county": "Izmir", "city": "Izmir"},
    {"name": "Karaburun", "country": "Turkey", "latitude": 38.6346, "longitude": 26.5124, "timezone": "Europe/Istanbul", "county": "Izmir", "city": "Izmir"},
    {"name": "Çeşme", "country": "Turkey", "latitude": 38.3069, "longitude": 26.3039, "timezone": "Europe/Istanbul", "county": "Izmir", "city": "Izmir"},
    {"name": "Aliağa", "country": "Turkey", "latitude": 38.8013, "longitude": 27.0663, "timezone": "Europe/Istanbul", "county": "Izmir", "city": "Izmir"},
    {"name": "Bergama", "country": "Turkey", "latitude": 39.1083, "longitude": 27.1816, "timezone": "Europe/Istanbul", "county": "Izmir", "city": "Izmir"},
    {"name": "Torbalı", "country": "Turkey", "latitude": 38.1523, "longitude": 27.8657, "timezone": "Europe/Istanbul", "county": "Izmir", "city": "Izmir"},
    {"name": "Menemen", "country": "Turkey", "latitude": 38.6075, "longitude": 27.0715, "timezone": "Europe/Istanbul", "county": "Izmir", "city": "Izmir"},
    
    {"name": "Nilüfer", "country": "Turkey", "latitude": 40.2158, "longitude": 28.9553, "timezone": "Europe/Istanbul", "county": "Bursa", "city": "Bursa"},
    {"name": "Osmangazi", "country": "Turkey", "latitude": 40.2149, "longitude": 29.0092, "timezone": "Europe/Istanbul", "county": "Bursa", "city": "Bursa"},
    {"name": "Yıldırım", "country": "Turkey", "latitude": 40.1986, "longitude": 29.0818, "timezone": "Europe/Istanbul", "county": "Bursa", "city": "Bursa"},
    {"name": "Gemlik", "country": "Turkey", "latitude": 40.4297, "longitude": 29.1597, "timezone": "Europe/Istanbul", "county": "Bursa", "city": "Bursa"},
    {"name": "İnegöl", "country": "Turkey", "latitude": 40.1054, "longitude": 29.5106, "timezone": "Europe/Istanbul", "county": "Bursa", "city": "Bursa"},
    {"name": "Mudanya", "country": "Turkey", "latitude": 40.3369, "longitude": 28.9575, "timezone": "Europe/Istanbul", "county": "Bursa", "city": "Bursa"},
    {"name": "Mustafakemalpaşa", "country": "Turkey", "latitude": 40.0333, "longitude": 28.4167, "timezone": "Europe/Istanbul", "county": "Bursa", "city": "Bursa"},
    {"name": "Orhangazi", "country": "Turkey", "latitude": 40.4878, "longitude": 29.3083, "timezone": "Europe/Istanbul", "county": "Bursa", "city": "Bursa"},
    {"name": "Karacabey", "country": "Turkey", "latitude": 40.2137, "longitude": 28.3653, "timezone": "Europe/Istanbul", "county": "Bursa", "city": "Bursa"},
    {"name": "Gürsu", "country": "Turkey", "latitude": 40.2187, "longitude": 28.8617, "timezone": "Europe/Istanbul", "county": "Bursa", "city": "Bursa"},
    
    {"name": "Konyaaltı", "country": "Turkey", "latitude": 36.8848, "longitude": 30.6449, "timezone": "Europe/Istanbul", "county": "Antalya", "city": "Antalya"},
    {"name": "Muratpaşa", "country": "Turkey", "latitude": 36.8847, "longitude": 30.7055, "timezone": "Europe/Istanbul", "county": "Antalya", "city": "Antalya"},
    {"name": "Alanya", "country": "Turkey", "latitude": 36.5628, "longitude": 31.9995, "timezone": "Europe/Istanbul", "county": "Antalya", "city": "Antalya"},
    {"name": "Serik", "country": "Turkey", "latitude": 36.9179, "longitude": 31.0999, "timezone": "Europe/Istanbul", "county": "Antalya", "city": "Antalya"},
    {"name": "Manavgat", "country": "Turkey", "latitude": 36.7872, "longitude": 31.4414, "timezone": "Europe/Istanbul", "county": "Antalya", "city": "Antalya"},
    {"name": "Kaş", "country": "Turkey", "latitude": 36.1988, "longitude": 29.6394, "timezone": "Europe/Istanbul", "county": "Antalya", "city": "Antalya"},
    {"name": "Kemer", "country": "Turkey", "latitude": 36.5977, "longitude": 30.5351, "timezone": "Europe/Istanbul", "county": "Antalya", "city": "Antalya"},
    {"name": "Finike", "country": "Turkey", "latitude": 36.3159, "longitude": 30.1524, "timezone": "Europe/Istanbul", "county": "Antalya", "city": "Antalya"},
    {"name": "Kumluca", "country": "Turkey", "latitude": 36.3644, "longitude": 30.0448, "timezone": "Europe/Istanbul", "county": "Antalya", "city": "Antalya"},
    {"name": " Aksu", "country": "Turkey", "latitude": 36.9477, "longitude": 30.8569, "timezone": "Europe/Istanbul", "county": "Antalya", "city": "Antalya"},
    
    {"name": "Şahinbey", "country": "Turkey", "latitude": 37.0662, "longitude": 37.3833, "timezone": "Europe/Istanbul", "county": "Gaziantep", "city": "Gaziantep"},
    {"name": "Şehitkamil", "country": "Turkey", "latitude": 37.0858, "longitude": 37.3436, "timezone": "Europe/Istanbul", "county": "Gaziantep", "city": "Gaziantep"},
    {"name": "Nizip", "country": "Turkey", "latitude": 37.0106, "longitude": 37.7907, "timezone": "Europe/Istanbul", "county": "Gaziantep", "city": "Gaziantep"},
    {"name": "İslahiye", "country": "Turkey", "latitude": 37.0281, "longitude": 36.6306, "timezone": "Europe/Istanbul", "county": "Gaziantep", "city": "Gaziantep"},
    {"name": "Nurdağı", "country": "Turkey", "latitude": 37.1631, "longitude": 36.7428, "timezone": "Europe/Istanbul", "county": "Gaziantep", "city": "Gaziantep"},
    {"name": "Araban", "country": "Turkey", "latitude": 37.4244, "longitude": 37.7078, "timezone": "Europe/Istanbul", "county": "Gaziantep", "city": "Gaziantep"},
    {"name": "Karkamış", "country": "Turkey", "latitude": 36.8353, "longitude": 38.0156, "timezone": "Europe/Istanbul", "county": "Gaziantep", "city": "Gaziantep"},
    {"name": "Yavuzeli", "country": "Turkey", "latitude": 37.3167, "longitude": 37.3833, "timezone": "Europe/Istanbul", "county": "Gaziantep", "city": "Gaziantep"},
    
    {"name": "Selçuklu", "country": "Turkey", "latitude": 37.9438, "longitude": 32.4932, "timezone": "Europe/Istanbul", "county": "Konya", "city": "Konya"},
    {"name": "Karatay", "country": "Turkey", "latitude": 37.9845, "longitude": 32.4597, "timezone": "Europe/Istanbul", "county": "Konya", "city": "Konya"},
    {"name": "Meram", "country": "Turkey", "latitude": 37.8746, "longitude": 32.4932, "timezone": "Europe/Istanbul", "county": "Konya", "city": "Konya"},
    {"name": "Akşehir", "country": "Turkey", "latitude": 38.3575, "longitude": 31.4164, "timezone": "Europe/Istanbul", "county": "Konya", "city": "Konya"},
    {"name": "Beyşehir", "country": "Turkey", "latitude": 37.6745, "longitude": 31.7258, "timezone": "Europe/Istanbul", "county": "Konya", "city": "Konya"},
    {"name": "Sille", "country": "Turkey", "latitude": 37.9247, "longitude": 32.2899, "timezone": "Europe/Istanbul", "county": "Konya", "city": "Konya"},
    {"name": "Çumra", "country": "Turkey", "latitude": 37.5394, "longitude": 32.7805, "timezone": "Europe/Istanbul", "county": "Konya", "city": "Konya"},
    {"name": "Seydişehir", "country": "Turkey", "latitude": 37.4197, "longitude": 31.8483, "timezone": "Europe/Istanbul", "county": "Konya", "city": "Konya"},
    {"name": "Ereğli", "country": "Turkey", "latitude": 37.5095, "longitude": 34.0463, "timezone": "Europe/Istanbul", "county": "Konya", "city": "Konya"},
    {"name": "Kulu", "country": "Turkey", "latitude": 39.0667, "longitude": 33.0833, "timezone": "Europe/Istanbul", "county": "Konya", "city": "Konya"},
    
    {"name": "Yenişehir", "country": "Turkey", "latitude": 36.8, "longitude": 34.6333, "timezone": "Europe/Istanbul", "county": "Mersin", "city": "Mersin"},
    {"name": "Akdeniz", "country": "Turkey", "latitude": 36.5937, "longitude": 34.3783, "timezone": "Europe/Istanbul", "county": "Mersin", "city": "Mersin"},
    {"name": "Toroslar", "country": "Turkey", "latitude": 36.7214, "longitude": 34.3783, "timezone": "Europe/Istanbul", "county": "Mersin", "city": "Mersin"},
    {"name": "Mezitli", "country": "Turkey", "latitude": 36.7658, "longitude": 34.4828, "timezone": "Europe/Istanbul", "county": "Mersin", "city": "Mersin"},
    {"name": "Silifke", "country": "Turkey", "latitude": 36.3767, "longitude": 33.9306, "timezone": "Europe/Istanbul", "county": "Mersin", "city": "Mersin"},
    {"name": "Anamur", "country": "Turkey", "latitude": 36.0758, "longitude": 32.8369, "timezone": "Europe/Istanbul", "county": "Mersin", "city": "Mersin"},
    {"name": "Erdemli", "country": "Turkey", "latitude": 36.6061, "longitude": 34.3072, "timezone": "Europe/Istanbul", "county": "Mersin", "city": "Mersin"},
    {"name": "Tarsus", "country": "Turkey", "latitude": 36.9217, "longitude": 34.8928, "timezone": "Europe/Istanbul", "county": "Mersin", "city": "Mersin"},
    {"name": "Mut", "country": "Turkey", "latitude": 36.6444, "longitude": 33.4375, "timezone": "Europe/Istanbul", "county": "Mersin", "city": "Mersin"},
    {"name": "Bozyazı", "country": "Turkey", "latitude": 36.1081, "longitude": 32.9667, "timezone": "Europe/Istanbul", "county": "Mersin", "city": "Mersin"},
    
    {"name": "Bağlar", "country": "Turkey", "latitude": 37.9144, "longitude": 40.2306, "timezone": "Europe/Istanbul", "county": "Diyarbakir", "city": "Diyarbakir"},
    {"name": "Kayapınar", "country": "Turkey", "latitude": 37.8539, "longitude": 40.1925, "timezone": "Europe/Istanbul", "county": "Diyarbakir", "city": "Diyarbakir"},
    {"name": "Yenişehir", "country": "Turkey", "latitude": 37.9094, "longitude": 40.1747, "timezone": "Europe/Istanbul", "county": "Diyarbakir", "city": "Diyarbakir"},
    {"name": "Sur", "country": "Turkey", "latitude": 38.0125, "longitude": 40.2414, "timezone": "Europe/Istanbul", "county": "Diyarbakir", "city": "Diyarbakir"},
    {"name": "Bismil", "country": "Turkey", "latitude": 37.8478, "longitude": 40.4194, "timezone": "Europe/Istanbul", "county": "Diyarbakir", "city": "Diyarbakir"},
    {"name": "Çermik", "country": "Turkey", "latitude": 38.1369, "longitude": 39.4547, "timezone": "Europe/Istanbul", "county": "Diyarbakir", "city": "Diyarbakir"},
    {"name": "Çınar", "country": "Turkey", "latitude": 37.7583, "longitude": 40.7694, "timezone": "Europe/Istanbul", "county": "Diyarbakir", "city": "Diyarbakir"},
    {"name": "Dicle", "country": "Turkey", "latitude": 38.0575, "longitude": 40.6689, "timezone": "Europe/Istanbul", "county": "Diyarbakir", "city": "Diyarbakir"},
    {"name": "Ergani", "country": "Turkey", "latitude": 38.2775, "longitude": 39.7644, "timezone": "Europe/Istanbul", "county": "Diyarbakir", "city": "Diyarbakir"},
    {"name": "Hani", "country": "Turkey", "latitude": 38.4097, "longitude": 40.4042, "timezone": "Europe/Istanbul", "county": "Diyarbakir", "city": "Diyarbakir"},
    
    {"name": "Tepebaşı", "country": "Turkey", "latitude": 39.7667, "longitude": 30.5256, "timezone": "Europe/Istanbul", "county": "Eskisehir", "city": "Eskisehir"},
    {"name": "Odunpazarı", "country": "Turkey", "latitude": 39.7767, "longitude": 30.5256, "timezone": "Europe/Istanbul", "county": "Eskisehir", "city": "Eskisehir"},
    {"name": "Sivrihisar", "country": "Turkey", "latitude": 39.4489, "longitude": 31.5356, "timezone": "Europe/Istanbul", "county": "Eskisehir", "city": "Eskisehir"},
    {"name": "Çifteler", "country": "Turkey", "latitude": 39.3833, "longitude": 31.0333, "timezone": "Europe/Istanbul", "county": "Eskisehir", "city": "Eskisehir"},
    {"name": "Alpu", "country": "Turkey", "latitude": 39.8167, "longitude": 30.9667, "timezone": "Europe/Istanbul", "county": "Eskisehir", "city": "Eskisehir"},
    {"name": "Mihalgazi", "country": "Turkey", "latitude": 40.0333, "longitude": 30.5667, "timezone": "Europe/Istanbul", "county": "Eskisehir", "city": "Eskisehir"},
    {"name": "İnönü", "country": "Turkey", "latitude": 39.8167, "longitude": 30.15, "timezone": "Europe/Istanbul", "county": "Eskisehir", "city": "Eskisehir"},
    {"name": "Günyüzü", "country": "Turkey", "latitude": 39.6167, "longitude": 31.1833, "timezone": "Europe/Istanbul", "county": "Eskisehir", "city": "Eskisehir"},
    {"name": "Sarıcakaya", "country": "Turkey", "latitude": 40.0333, "longitude": 30.3833, "timezone": "Europe/Istanbul", "county": "Eskisehir", "city": "Eskisehir"},
    {"name": "Mihalıççık", "country": "Turkey", "latitude": 39.9167, "longitude": 31.0667, "timezone": "Europe/Istanbul", "county": "Eskisehir", "city": "Eskisehir"},
    
    {"name": "Atakum", "country": "Turkey", "latitude": 41.2928, "longitude": 36.3313, "timezone": "Europe/Istanbul", "county": "Samsun", "city": "Samsun"},
    {"name": "Canik", "country": "Turkey", "latitude": 41.2667, "longitude": 36.2667, "timezone": "Europe/Istanbul", "county": "Samsun", "city": "Samsun"},
    {"name": "İlkadım", "country": "Turkey", "latitude": 41.2928, "longitude": 36.3313, "timezone": "Europe/Istanbul", "county": "Samsun", "city": "Samsun"},
    {"name": "Bafra", "country": "Turkey", "latitude": 41.5675, "longitude": 35.9078, "timezone": "Europe/Istanbul", "county": "Samsun", "city": "Samsun"},
    {"name": "Çarşamba", "country": "Turkey", "latitude": 41.1969, "longitude": 36.7294, "timezone": "Europe/Istanbul", "county": "Samsun", "city": "Samsun"},
    {"name": "Terme", "country": "Turkey", "latitude": 41.2097, "longitude": 36.975, "timezone": "Europe/Istanbul", "county": "Samsun", "city": "Samsun"},
    {"name": "Vezirköprü", "country": "Turkey", "latitude": 41.1433, "longitude": 35.4514, "timezone": "Europe/Istanbul", "county": "Samsun", "city": "Samsun"},
    {"name": "Alaçam", "country": "Turkey", "latitude": 41.6333, "longitude": 35.9833, "timezone": "Europe/Istanbul", "county": "Samsun", "city": "Samsun"},
    {"name": "Havza", "country": "Turkey", "latitude": 40.9678, "longitude": 36.0508, "timezone": "Europe/Istanbul", "county": "Samsun", "city": "Samsun"},
    {"name": "Kavak", "country": "Turkey", "latitude": 41.05, "longitude": 35.8667, "timezone": "Europe/Istanbul", "county": "Samsun", "city": "Samsun"},
    
    {"name": "Pamukkale", "country": "Turkey", "latitude": 37.7765, "longitude": 29.0864, "timezone": "Europe/Istanbul", "county": "Denizli", "city": "Denizli"},
    {"name": "Merkezefendi", "country": "Turkey", "latitude": 37.8197, "longitude": 29.0861, "timezone": "Europe/Istanbul", "county": "Denizli", "city": "Denizli"},
    {"name": "Acıpayam", "country": "Turkey", "latitude": 37.2625, "longitude": 29.3478, "timezone": "Europe/Istanbul", "county": "Denizli", "city": "Denizli"},
    {"name": "Tavas", "country": "Turkey", "latitude": 37.5658, "longitude": 29.0344, "timezone": "Europe/Istanbul", "county": "Denizli", "city": "Denizli"},
    {"name": "Sarayköy", "country": "Turkey", "latitude": 37.9269, "longitude": 28.9242, "timezone": "Europe/Istanbul", "county": "Denizli", "city": "Denizli"},
    {"name": "Buldan", "country": "Turkey", "latitude": 38.0389, "longitude": 28.8328, "timezone": "Europe/Istanbul", "county": "Denizli", "city": "Denizli"},
    {"name": "Çivril", "country": "Turkey", "latitude": 38.3069, "longitude": 29.7403, "timezone": "Europe/Istanbul", "county": "Denizli", "city": "Denizli"},
    {"name": "Kale", "country": "Turkey", "latitude": 37.45, "longitude": 28.55, "timezone": "Europe/Istanbul", "county": "Denizli", "city": "Denizli"},
    {"name": "Honaz", "country": "Turkey", "latitude": 37.6497, "longitude": 29.2608, "timezone": "Europe/Istanbul", "county": "Denizli", "city": "Denizli"},
    {"name": "Çal", "country": "Turkey", "latitude": 37.9667, "longitude": 29.4, "timezone": "Europe/Istanbul", "county": "Denizli", "city": "Denizli"},
    
    {"name": "Onikişubat", "country": "Turkey", "latitude": 37.5858, "longitude": 36.9371, "timezone": "Europe/Istanbul", "county": "Kahramanmaras", "city": "Kahramanmaras"},
    {"name": "Dulkadiroğlu", "country": "Turkey", "latitude": 37.5992, "longitude": 36.9228, "timezone": "Europe/Istanbul", "county": "Kahramanmaras", "city": "Kahramanmaras"},
    {"name": "Elbistan", "country": "Turkey", "latitude": 38.2047, "longitude": 37.1961, "timezone": "Europe/Istanbul", "county": "Kahramanmaras", "city": "Kahramanmaras"},
    {"name": "Afşin", "country": "Turkey", "latitude": 38.2492, "longitude": 36.5639, "timezone": "Europe/Istanbul", "county": "Kahramanmaras", "city": "Kahramanmaras"},
    {"name": "Türkoğlu", "country": "Turkey", "latitude": 37.3869, "longitude": 36.8472, "timezone": "Europe/Istanbul", "county": "Kahramanmaras", "city": "Kahramanmaras"},
    {"name": "Pazarcık", "country": "Turkey", "latitude": 37.5144, "longitude": 37.1361, "timezone": "Europe/Istanbul", "county": "Kahramanmaras", "city": "Kahramanmaras"},
    {"name": "Göksun", "country": "Turkey", "latitude": 38.0256, "longitude": 36.4972, "timezone": "Europe/Istanbul", "county": "Kahramanmaras", "city": "Kahramanmaras"},
    {"name": "Andırın", "country": "Turkey", "latitude": 37.5783, "longitude": 36.3522, "timezone": "Europe/Istanbul", "county": "Kahramanmaras", "city": "Kahramanmaras"},
    
    {"name": "Yeşilyurt", "country": "Turkey", "latitude": 38.3552, "longitude": 38.3095, "timezone": "Europe/Istanbul", "county": "Malatya", "city": "Malatya"},
    {"name": "Battalgazi", "country": "Turkey", "latitude": 38.4297, "longitude": 38.3486, "timezone": "Europe/Istanbul", "county": "Malatya", "city": "Malatya"},
    {"name": "Doğanşehir", "country": "Turkey", "latitude": 38.0939, "longitude": 38.0319, "timezone": "Europe/Istanbul", "county": "Malatya", "city": "Malatya"},
    {"name": "Akçadağ", "country": "Turkey", "latitude": 38.3333, "longitude": 37.7167, "timezone": "Europe/Istanbul", "county": "Malatya", "city": "Malatya"},
    {"name": "Darende", "country": "Turkey", "latitude": 38.5439, "longitude": 37.2617, "timezone": "Europe/Istanbul", "county": "Malatya", "city": "Malatya"},
    {"name": "Pütürge", "country": "Turkey", "latitude": 38.2192, "longitude": 38.8694, "timezone": "Europe/Istanbul", "county": "Malatya", "city": "Malatya"},
    {"name": "Yazıhan", "country": "Turkey", "latitude": 38.5833, "longitude": 37.9167, "timezone": "Europe/Istanbul", "county": "Malatya", "city": "Malatya"},
    {"name": "Kuluncak", "country": "Turkey", "latitude": 38.85, "longitude": 37.8333, "timezone": "Europe/Istanbul", "county": "Malatya", "city": "Malatya"},
    
    {"name": "Yakutiye", "country": "Turkey", "latitude": 39.9043, "longitude": 41.2679, "timezone": "Europe/Istanbul", "county": "Erzurum", "city": "Erzurum"},
    {"name": "Palandöken", "country": "Turkey", "latitude": 39.9028, "longitude": 41.2775, "timezone": "Europe/Istanbul", "county": "Erzurum", "city": "Erzurum"},
    {"name": "Aziziye", "country": "Turkey", "latitude": 39.95, "longitude": 41.2167, "timezone": "Europe/Istanbul", "county": "Erzurum", "city": "Erzurum"},
    {"name": "Horasan", "country": "Turkey", "latitude": 40.05, "longitude": 42.1667, "timezone": "Europe/Istanbul", "county": "Erzurum", "city": "Erzurum"},
    {"name": "Oltu", "country": "Turkey", "latitude": 40.5514, "longitude": 41.9861, "timezone": "Europe/Istanbul", "county": "Erzurum", "city": "Erzurum"},
    {"name": "Tortum", "country": "Turkey", "latitude": 40.3, "longitude": 41.5333, "timezone": "Europe/Istanbul", "county": "Erzurum", "city": "Erzurum"},
    {"name": "Karaçoban", "country": "Turkey", "latitude": 40.0333, "longitude": 42.0, "timezone": "Europe/Istanbul", "county": "Erzurum", "city": "Erzurum"},
    {"name": "Hınıs", "country": "Turkey", "latitude": 39.3667, "longitude": 41.6833, "timezone": "Europe/Istanbul", "county": "Erzurum", "city": "Erzurum"},
    
    {"name": "İpekyolu", "country": "Turkey", "latitude": 38.4891, "longitude": 43.4089, "timezone": "Europe/Istanbul", "county": "Van", "city": "Van"},
    {"name": "Tuşba", "country": "Turkey", "latitude": 38.5167, "longitude": 43.3833, "timezone": "Europe/Istanbul", "county": "Van", "city": "Van"},
    {"name": "Edremit", "country": "Turkey", "latitude": 38.4167, "longitude": 43.25, "timezone": "Europe/Istanbul", "county": "Van", "city": "Van"},
    {"name": "Çaldıran", "country": "Turkey", "latitude": 39.1061, "longitude": 43.9258, "timezone": "Europe/Istanbul", "county": "Van", "city": "Van"},
    {"name": "Başkale", "country": "Turkey", "latitude": 38.0333, "longitude": 44.0167, "timezone": "Europe/Istanbul", "county": "Van", "city": "Van"},
    {"name": "Özalp", "country": "Turkey", "latitude": 39.4619, "longitude": 43.7128, "timezone": "Europe/Istanbul", "county": "Van", "city": "Van"},
    {"name": "Muradiye", "country": "Turkey", "latitude": 39.0667, "longitude": 43.7167, "timezone": "Europe/Istanbul", "county": "Van", "city": "Van"},
    {"name": "Saray", "country": "Turkey", "latitude": 38.65, "longitude": 44.0833, "timezone": "Europe/Istanbul", "county": "Van", "city": "Van"},
    
    # Remaining provinces without districts (using city name as county)
    {"name": "Sivas", "country": "Turkey", "latitude": 39.7477, "longitude": 37.0179, "timezone": "Europe/Istanbul", "county": "Sivas", "city": "Sivas"},
    {"name": "Trabzon", "country": "Turkey", "latitude": 41.0027, "longitude": 39.7168, "timezone": "Europe/Istanbul", "county": "Trabzon", "city": "Trabzon"},
    {"name": "Ordu", "country": "Turkey", "latitude": 40.9839, "longitude": 37.8764, "timezone": "Europe/Istanbul", "county": "Ordu", "city": "Ordu"},
    {"name": "Giresun", "country": "Turkey", "latitude": 40.9128, "longitude": 38.3895, "timezone": "Europe/Istanbul", "county": "Giresun", "city": "Giresun"},
    {"name": "Rize", "country": "Turkey", "latitude": 41.0201, "longitude": 40.5234, "timezone": "Europe/Istanbul", "county": "Rize", "city": "Rize"},
    {"name": "Artvin", "country": "Turkey", "latitude": 41.1828, "longitude": 41.8183, "timezone": "Europe/Istanbul", "county": "Artvin", "city": "Artvin"},
    {"name": "Gümüşhane", "country": "Turkey", "latitude": 40.4386, "longitude": 39.5086, "timezone": "Europe/Istanbul", "county": "Gumushane", "city": "Gumushane"},
    {"name": "Bayburt", "country": "Turkey", "latitude": 40.2552, "longitude": 40.2249, "timezone": "Europe/Istanbul", "county": "Bayburt", "city": "Bayburt"},
    {"name": "Amasya", "country": "Turkey", "latitude": 40.6499, "longitude": 35.8353, "timezone": "Europe/Istanbul", "county": "Amasya", "city": "Amasya"},
    {"name": "Tokat", "country": "Turkey", "latitude": 40.3167, "longitude": 36.5500, "timezone": "Europe/Istanbul", "county": "Tokat", "city": "Tokat"},
    {"name": "Çorum", "country": "Turkey", "latitude": 40.5489, "longitude": 34.9533, "timezone": "Europe/Istanbul", "county": "Corum", "city": "Corum"},
    {"name": "Yozgat", "country": "Turkey", "latitude": 39.8181, "longitude": 34.8147, "timezone": "Europe/Istanbul", "county": "Yozgat", "city": "Yozgat"},
    {"name": "Kırıkkale", "country": "Turkey", "latitude": 39.8468, "longitude": 33.5153, "timezone": "Europe/Istanbul", "county": "Kirikkale", "city": "Kirikkale"},
    {"name": "Kırşehir", "country": "Turkey", "latitude": 39.1425, "longitude": 34.1709, "timezone": "Europe/Istanbul", "county": "Kirsehir", "city": "Kirsehir"},
    {"name": "Nevşehir", "country": "Turkey", "latitude": 38.6939, "longitude": 34.6857, "timezone": "Europe/Istanbul", "county": "Nevsehir", "city": "Nevsehir"},
    {"name": "Aksaray", "country": "Turkey", "latitude": 38.3687, "longitude": 34.0370, "timezone": "Europe/Istanbul", "county": "Aksaray", "city": "Aksaray"},
    {"name": "Niğde", "country": "Turkey", "latitude": 37.9667, "longitude": 34.6939, "timezone": "Europe/Istanbul", "county": "Nigde", "city": "Nigde"},
    {"name": "Kırklareli", "country": "Turkey", "latitude": 41.7333, "longitude": 27.2167, "timezone": "Europe/Istanbul", "county": "Kirklareli", "city": "Kirklareli"},
    {"name": "Edirne", "country": "Turkey", "latitude": 41.6771, "longitude": 26.5557, "timezone": "Europe/Istanbul", "county": "Edirne", "city": "Edirne"},
    {"name": "Tekirdağ", "country": "Turkey", "latitude": 40.9839, "longitude": 27.5091, "timezone": "Europe/Istanbul", "county": "Tekirdag", "city": "Tekirdag"},
    {"name": "Çanakkale", "country": "Turkey", "latitude": 40.1553, "longitude": 26.4142, "timezone": "Europe/Istanbul", "county": "Canakkale", "city": "Canakkale"},
    {"name": "Balıkesir", "country": "Turkey", "latitude": 39.6484, "longitude": 27.8826, "timezone": "Europe/Istanbul", "county": "Balikesir", "city": "Balikesir"},
    {"name": "Manisa", "country": "Turkey", "latitude": 38.6191, "longitude": 27.4289, "timezone": "Europe/Istanbul", "county": "Manisa", "city": "Manisa"},
    {"name": "Uşak", "country": "Turkey", "latitude": 38.6823, "longitude": 29.4082, "timezone": "Europe/Istanbul", "county": "Usak", "city": "Usak"},
    {"name": "Kütahya", "country": "Turkey", "latitude": 39.4242, "longitude": 29.9833, "timezone": "Europe/Istanbul", "county": "Kutahya", "city": "Kutahya"},
    {"name": "Afyonkarahisar", "country": "Turkey", "latitude": 38.7312, "longitude": 30.5387, "timezone": "Europe/Istanbul", "county": "Afyon", "city": "Afyon"},
    {"name": "Burdur", "country": "Turkey", "latitude": 37.4613, "longitude": 30.0665, "timezone": "Europe/Istanbul", "county": "Burdur", "city": "Burdur"},
    {"name": "Isparta", "country": "Turkey", "latitude": 37.7648, "longitude": 30.5566, "timezone": "Europe/Istanbul", "county": "Isparta", "city": "Isparta"},
    {"name": "Kocaeli", "country": "Turkey", "latitude": 40.8533, "longitude": 29.8815, "timezone": "Europe/Istanbul", "county": "Kocaeli", "city": "Kocaeli"},
    {"name": "Sakarya", "country": "Turkey", "latitude": 40.6940, "longitude": 30.4358, "timezone": "Europe/Istanbul", "county": "Sakarya", "city": "Sakarya"},
    {"name": "Düzce", "country": "Turkey", "latitude": 40.8438, "longitude": 31.1565, "timezone": "Europe/Istanbul", "county": "Duzce", "city": "Duzce"},
    {"name": "Bolu", "country": "Turkey", "latitude": 40.7355, "longitude": 31.6061, "timezone": "Europe/Istanbul", "county": "Bolu", "city": "Bolu"},
    {"name": "Zonguldak", "country": "Turkey", "latitude": 41.4564, "longitude": 31.7987, "timezone": "Europe/Istanbul", "county": "Zonguldak", "city": "Zonguldak"},
    {"name": "Karabük", "country": "Turkey", "latitude": 41.2061, "longitude": 32.6204, "timezone": "Europe/Istanbul", "county": "Karabuk", "city": "Karabuk"},
    {"name": "Bartın", "country": "Turkey", "latitude": 41.6344, "longitude": 32.3375, "timezone": "Europe/Istanbul", "county": "Bartin", "city": "Bartin"},
    {"name": "Kastamonu", "country": "Turkey", "latitude": 41.3887, "longitude": 33.7827, "timezone": "Europe/Istanbul", "county": "Kastamonu", "city": "Kastamonu"},
    {"name": "Çankırı", "country": "Turkey", "latitude": 40.6013, "longitude": 33.6134, "timezone": "Europe/Istanbul", "county": "Cankiri", "city": "Cankiri"},
    {"name": "Sinop", "country": "Turkey", "latitude": 42.0231, "longitude": 35.1531, "timezone": "Europe/Istanbul", "county": "Sinop", "city": "Sinop"},
    {"name": "Aydın", "country": "Turkey", "latitude": 37.8560, "longitude": 27.8416, "timezone": "Europe/Istanbul", "county": "Aydin", "city": "Aydin"},
    {"name": "Muğla", "country": "Turkey", "latitude": 37.2153, "longitude": 28.3636, "timezone": "Europe/Istanbul", "county": "Mugla", "city": "Mugla"},
    {"name": "Bilecik", "country": "Turkey", "latitude": 40.0567, "longitude": 30.0665, "timezone": "Europe/Istanbul", "county": "Bilecik", "city": "Bilecik"},
    {"name": "Yalova", "country": "Turkey", "latitude": 40.6500, "longitude": 29.2667, "timezone": "Europe/Istanbul", "county": "Yalova", "city": "Yalova"},
    {"name": "Karaman", "country": "Turkey", "latitude": 37.1759, "longitude": 33.2287, "timezone": "Europe/Istanbul", "county": "Karaman", "city": "Karaman"},
    {"name": "Kayseri", "country": "Turkey", "latitude": 38.7312, "longitude": 35.4787, "timezone": "Europe/Istanbul", "county": "Kayseri", "city": "Kayseri"},
    {"name": "Spor", "country": "Turkey", "latitude": 38.7312, "longitude": 35.4787, "timezone": "Europe/Istanbul", "county": "Kayseri", "city": "Kayseri"},
    {"name": "Talas", "country": "Turkey", "latitude": 38.6894, "longitude": 35.5519, "timezone": "Europe/Istanbul", "county": "Kayseri", "city": "Kayseri"},
    {"name": "Kocasinan", "country": "Turkey", "latitude": 38.7208, "longitude": 35.4872, "timezone": "Europe/Istanbul", "county": "Kayseri", "city": "Kayseri"},
    {"name": "Sarıoğlan", "country": "Turkey", "latitude": 39.1, "longitude": 35.7833, "timezone": "Europe/Istanbul", "county": "Kayseri", "city": "Kayseri"},
    {"name": "Yahyasaray", "country": "Turkey", "latitude": 38.9333, "longitude": 35.7833, "timezone": "Europe/Istanbul", "county": "Kayseri", "city": "Kayseri"},
    {"name": "Sarız", "country": "Turkey", "latitude": 38.4833, "longitude": 36.5, "timezone": "Europe/Istanbul", "county": "Kayseri", "city": "Kayseri"},
    {"name": "Tomarza", "country": "Turkey", "latitude": 38.4833, "longitude": 35.8, "timezone": "Europe/Istanbul", "county": "Kayseri", "city": "Kayseri"},
    {"name": "Yahyali", "country": "Turkey", "latitude": 38.1167, "longitude": 35.35, "timezone": "Europe/Istanbul", "county": "Kayseri", "city": "Kayseri"},
    {"name": "Kızık", "country": "Turkey", "latitude": 38.3, "longitude": 35.6333, "timezone": "Europe/Istanbul", "county": "Kayseri", "city": "Kayseri"},
    {"name": "Akkışla", "country": "Turkey", "latitude": 38.7333, "longitude": 36.05, "timezone": "Europe/Istanbul", "county": "Kayseri", "city": "Kayseri"},
    {"name": "Elazığ", "country": "Turkey", "latitude": 38.6810, "longitude": 39.2264, "timezone": "Europe/Istanbul", "county": "Elazig", "city": "Elazig"},
    {"name": "Keban", "country": "Turkey", "latitude": 38.7833, "longitude": 38.75, "timezone": "Europe/Istanbul", "county": "Elazig", "city": "Elazig"},
    {"name": "Palu", "country": "Turkey", "latitude": 38.6914, "longitude": 39.9328, "timezone": "Europe/Istanbul", "county": "Elazig", "city": "Elazig"},
    {"name": "Bingöl", "country": "Turkey", "latitude": 38.8855, "longitude": 40.4966, "timezone": "Europe/Istanbul", "county": "Bingol", "city": "Bingol"},
    {"name": "Genç", "country": "Turkey", "latitude": 38.75, "longitude": 40.5333, "timezone": "Europe/Istanbul", "county": "Bingol", "city": "Bingol"},
    {"name": "Karlıova", "country": "Turkey", "latitude": 39.0333, "longitude": 41.0333, "timezone": "Europe/Istanbul", "county": "Bingol", "city": "Bingol"},
    {"name": "Solhan", "country": "Turkey", "latitude": 38.95, "longitude": 41.05, "timezone": "Europe/Istanbul", "county": "Bingol", "city": "Bingol"},
    {"name": "Adaklı", "country": "Turkey", "latitude": 39.1667, "longitude": 40.0833, "timezone": "Europe/Istanbul", "county": "Bingol", "city": "Bingol"},
    {"name": "Muş", "country": "Turkey", "latitude": 38.9462, "longitude": 41.7539, "timezone": "Europe/Istanbul", "county": "Mus", "city": "Mus"},
    {"name": " Bulanık", "country": "Turkey", "latitude": 39.0833, "longitude": 42.0667, "timezone": "Europe/Istanbul", "county": "Mus", "city": "Mus"},
    {"name": "Varto", "country": "Turkey", "latitude": 39.1667, "longitude": 41.45, "timezone": "Europe/Istanbul", "county": "Mus", "city": "Mus"},
    {"name": "Hasköy", "country": "Turkey", "latitude": 38.9833, "longitude": 41.7, "timezone": "Europe/Istanbul", "county": "Mus", "city": "Mus"},
    {"name": "Korkut", "country": "Turkey", "latitude": 39.05, "longitude": 41.9833, "timezone": "Europe/Istanbul", "county": "Mus", "city": "Mus"},
    {"name": "Tunceli", "country": "Turkey", "latitude": 39.1079, "longitude": 39.5401, "timezone": "Europe/Istanbul", "county": "Tunceli", "city": "Tunceli"},
    {"name": "Pertek", "country": "Turkey", "latitude": 38.9667, "longitude": 39.3167, "timezone": "Europe/Istanbul", "county": "Tunceli", "city": "Tunceli"},
    {"name": "Pülümür", "country": "Turkey", "latitude": 39.45, "longitude": 39.8833, "timezone": "Europe/Istanbul", "county": "Tunceli", "city": "Tunceli"},
    {"name": "Çemişgezek", "country": "Turkey", "latitude": 39.0667, "longitude": 38.9, "timezone": "Europe/Istanbul", "county": "Tunceli", "city": "Tunceli"},
    {"name": "Ovacık", "country": "Turkey", "latitude": 39.35, "longitude": 39.2333, "timezone": "Europe/Istanbul", "county": "Tunceli", "city": "Tunceli"},
    {"name": "Hakkâri", "country": "Turkey", "latitude": 37.5744, "longitude": 43.7408, "timezone": "Europe/Istanbul", "county": "Hakkari", "city": "Hakkari"},
    {"name": "Yüksekova", "country": "Turkey", "latitude": 37.5667, "longitude": 44.2833, "timezone": "Europe/Istanbul", "county": "Hakkari", "city": "Hakkari"},
    {"name": "Şemdinli", "country": "Turkey", "latitude": 37.3167, "longitude": 44.8167, "timezone": "Europe/Istanbul", "county": "Hakkari", "city": "Hakkari"},
    {"name": "Derecik", "country": "Turkey", "latitude": 37.4833, "longitude": 44.55, "timezone": "Europe/Istanbul", "county": "Hakkari", "city": "Hakkari"},
    {"name": "Çukurca", "country": "Turkey", "latitude": 37.2333, "longitude": 44.3, "timezone": "Europe/Istanbul", "county": "Hakkari", "city": "Hakkari"},
    {"name": "Şanlıurfa", "country": "Turkey", "latitude": 37.1591, "longitude": 38.7969, "timezone": "Europe/Istanbul", "county": "Sanliurfa", "city": "Sanliurfa"},
    {"name": "Eyyübiye", "country": "Turkey", "latitude": 37.1591, "longitude": 38.7969, "timezone": "Europe/Istanbul", "county": "Sanliurfa", "city": "Sanliurfa"},
    {"name": "Haliliye", "country": "Turkey", "latitude": 37.1591, "longitude": 38.7969, "timezone": "Europe/Istanbul", "county": "Sanliurfa", "city": "Sanliurfa"},
    {"name": "Siverek", "country": "Turkey", "latitude": 37.75, "longitude": 39.0333, "timezone": "Europe/Istanbul", "county": "Sanliurfa", "city": "Sanliurfa"},
    {"name": "Viranşehir", "country": "Turkey", "latitude": 37.2333, "longitude": 39.7833, "timezone": "Europe/Istanbul", "county": "Sanliurfa", "city": "Sanliurfa"},
    {"name": "Akçakale", "country": "Turkey", "latitude": 36.7167, "longitude": 38.95, "timezone": "Europe/Istanbul", "county": "Sanliurfa", "city": "Sanliurfa"},
    {"name": "Suruç", "country": "Turkey", "latitude": 36.9833, "longitude": 38.4167, "timezone": "Europe/Istanbul", "county": "Sanliurfa", "city": "Sanliurfa"},
    {"name": "Birecik", "country": "Turkey", "latitude": 37.0333, "longitude": 37.9833, "timezone": "Europe/Istanbul", "county": "Sanliurfa", "city": "Sanliurfa"},
    {"name": "Ceylanpınar", "country": "Turkey", "latitude": 36.7184, "longitude": 40.0494, "timezone": "Europe/Istanbul", "county": "Sanliurfa", "city": "Sanliurfa"},
    {"name": "Şırnak", "country": "Turkey", "latitude": 37.4187, "longitude": 42.4918, "timezone": "Europe/Istanbul", "county": "Sirnak", "city": "Sirnak"},
    {"name": "Cizre", "country": "Turkey", "latitude": 37.3167, "longitude": 42.1833, "timezone": "Europe/Istanbul", "county": "Sirnak", "city": "Sirnak"},
    {"name": "Silopi", "country": "Turkey", "latitude": 37.2333, "longitude": 42.4667, "timezone": "Europe/Istanbul", "county": "Sirnak", "city": "Sirnak"},
    {"name": "İdil", "country": "Turkey", "latitude": 37.3333, "longitude": 41.9667, "timezone": "Europe/Istanbul", "county": "Sirnak", "city": "Sirnak"},
    {"name": "Uludere", "country": "Turkey", "latitude": 37.3833, "longitude": 42.7167, "timezone": "Europe/Istanbul", "county": "Sirnak", "city": "Sirnak"},
    {"name": "Görükle", "country": "Turkey", "latitude": 40.2333, "longitude": 28.9333, "timezone": "Europe/Istanbul", "county": "Bursa", "city": "Bursa"},
    {"name": "Siirt", "country": "Turkey", "latitude": 37.9333, "longitude": 41.9500, "timezone": "Europe/Istanbul", "county": "Siirt", "city": "Siirt"},
    {"name": "Baykan", "country": "Turkey", "latitude": 37.9167, "longitude": 41.8333, "timezone": "Europe/Istanbul", "county": "Siirt", "city": "Siirt"},
    {"name": "Eruh", "country": "Turkey", "latitude": 37.65, "longitude": 42.3167, "timezone": "Europe/Istanbul", "county": "Siirt", "city": "Siirt"},
    {"name": "Kurtalan", "country": "Turkey", "latitude": 37.9167, "longitude": 41.7, "timezone": "Europe/Istanbul", "county": "Siirt", "city": "Siirt"},
    {"name": "Pervari", "country": "Turkey", "latitude": 37.9333, "longitude": 42.5167, "timezone": "Europe/Istanbul", "county": "Siirt", "city": "Siirt"},
    {"name": "Aydınlar", "country": "Turkey", "latitude": 38.0833, "longitude": 41.9667, "timezone": "Europe/Istanbul", "county": "Siirt", "city": "Siirt"},
    {"name": "Bitlis", "country": "Turkey", "latitude": 38.4004, "longitude": 42.1095, "timezone": "Europe/Istanbul", "county": "Bitlis", "city": "Bitlis"},
    {"name": "Tatvan", "country": "Turkey", "latitude": 38.5, "longitude": 42.2833, "timezone": "Europe/Istanbul", "county": "Bitlis", "city": "Bitlis"},
    {"name": "Ahlat", "country": "Turkey", "latitude": 38.7667, "longitude": 42.4833, "timezone": "Europe/Istanbul", "county": "Bitlis", "city": "Bitlis"},
    {"name": "Güroymak", "country": "Turkey", "latitude": 38.5667, "longitude": 42.0333, "timezone": "Europe/Istanbul", "county": "Bitlis", "city": "Bitlis"},
    {"name": "Mutki", "country": "Turkey", "latitude": 38.4, "longitude": 41.75, "timezone": "Europe/Istanbul", "county": "Bitlis", "city": "Bitlis"},
    {"name": "Adilcevaz", "country": "Turkey", "latitude": 38.8, "longitude": 42.7333, "timezone": "Europe/Istanbul", "county": "Bitlis", "city": "Bitlis"},
    {"name": "Hizan", "country": "Turkey", "latitude": 38.2333, "longitude": 42.4167, "timezone": "Europe/Istanbul", "county": "Bitlis", "city": "Bitlis"},
    {"name": "Kilis", "country": "Turkey", "latitude": 36.7184, "longitude": 37.1212, "timezone": "Europe/Istanbul", "county": "Kilis", "city": "Kilis"},
    {"name": "Musabeyli", "country": "Turkey", "latitude": 36.7167, "longitude": 37.2, "timezone": "Europe/Istanbul", "county": "Kilis", "city": "Kilis"},
    {"name": "Elbeyli", "country": "Turkey", "latitude": 36.5833, "longitude": 37.2833, "timezone": "Europe/Istanbul", "county": "Kilis", "city": "Kilis"},
    {"name": "Polateli", "country": "Turkey", "latitude": 36.7, "longitude": 37.0, "timezone": "Europe/Istanbul", "county": "Kilis", "city": "Kilis"},
    {"name": "Mardin", "country": "Turkey", "latitude": 37.3212, "longitude": 40.7245, "timezone": "Europe/Istanbul", "county": "Mardin", "city": "Mardin"},
    {"name": "Kızıltepe", "country": "Turkey", "latitude": 37.2, "longitude": 40.5833, "timezone": "Europe/Istanbul", "county": "Mardin", "city": "Mardin"},
    {"name": "Midyat", "country": "Turkey", "latitude": 37.4333, "longitude": 41.3833, "timezone": "Europe/Istanbul", "county": "Mardin", "city": "Mardin"},
    {"name": "Nusaybin", "country": "Turkey", "latitude": 37.0667, "longitude": 41.2167, "timezone": "Europe/Istanbul", "county": "Mardin", "city": "Mardin"},
    {"name": "Derik", "country": "Turkey", "latitude": 36.7833, "longitude": 39.2833, "timezone": "Europe/Istanbul", "county": "Mardin", "city": "Mardin"},
    {"name": "Mazıdağı", "country": "Turkey", "latitude": 37.4833, "longitude": 40.4833, "timezone": "Europe/Istanbul", "county": "Mardin", "city": "Mardin"},
    {"name": "Batman", "country": "Turkey", "latitude": 37.8812, "longitude": 41.1351, "timezone": "Europe/Istanbul", "county": "Batman", "city": "Batman"},
    {"name": "Kozluk", "country": "Turkey", "latitude": 38.5, "longitude": 41.4833, "timezone": "Europe/Istanbul", "county": "Batman", "city": "Batman"},
    {"name": "Sason", "country": "Turkey", "latitude": 38.25, "longitude": 41.0833, "timezone": "Europe/Istanbul", "county": "Batman", "city": "Batman"},
    {"name": "Beşiri", "country": "Turkey", "latitude": 38.0333, "longitude": 41.8833, "timezone": "Europe/Istanbul", "county": "Batman", "city": "Batman"},
    {"name": "Gercüş", "country": "Turkey", "latitude": 37.5667, "longitude": 41.9, "timezone": "Europe/Istanbul", "county": "Batman", "city": "Batman"},
    {"name": "Sahil", "country": "Turkey", "latitude": 37.6167, "longitude": 41.55, "timezone": "Europe/Istanbul", "county": "Batman", "city": "Batman"},
    {"name": "Iğdır", "country": "Turkey", "latitude": 39.9167, "longitude": 44.0333, "timezone": "Europe/Istanbul", "county": "Igdir", "city": "Igdir"},
    {"name": "Aralık", "country": "Turkey", "latitude": 39.95, "longitude": 44.5, "timezone": "Europe/Istanbul", "county": "Igdir", "city": "Igdir"},
    {"name": "Tuzluca", "country": "Turkey", "latitude": 39.9167, "longitude": 43.65, "timezone": "Europe/Istanbul", "county": "Igdir", "city": "Igdir"},
    {"name": "Karakoyunlu", "country": "Turkey", "latitude": 40.0, "longitude": 43.6333, "timezone": "Europe/Istanbul", "county": "Igdir", "city": "Igdir"},
    {"name": "Ardahan", "country": "Turkey", "latitude": 41.1105, "longitude": 42.7022, "timezone": "Europe/Istanbul", "county": "Ardahan", "city": "Ardahan"},
    {"name": "Göle", "country": "Turkey", "latitude": 40.7833, "longitude": 42.5833, "timezone": "Europe/Istanbul", "county": "Ardahan", "city": "Ardahan"},
    {"name": "Çıldır", "country": "Turkey", "latitude": 41.1333, "longitude": 43.1333, "timezone": "Europe/Istanbul", "county": "Ardahan", "city": "Ardahan"},
    {"name": "Damal", "country": "Turkey", "latitude": 41.3167, "longitude": 42.85, "timezone": "Europe/Istanbul", "county": "Ardahan", "city": "Ardahan"},
    {"name": "Posof", "country": "Turkey", "latitude": 41.5167, "longitude": 42.7333, "timezone": "Europe/Istanbul", "county": "Ardahan", "city": "Ardahan"},
    {"name": "Hanak", "country": "Turkey", "latitude": 41.2167, "longitude": 42.6833, "timezone": "Europe/Istanbul", "county": "Ardahan", "city": "Ardahan"},
    {"name": "Hatay", "country": "Turkey", "latitude": 36.4018, "longitude": 36.3498, "timezone": "Europe/Istanbul", "county": "Hatay", "city": "Hatay"},
    {"name": "Antakya", "country": "Turkey", "latitude": 36.4018, "longitude": 36.3498, "timezone": "Europe/Istanbul", "county": "Hatay", "city": "Hatay"},
    {"name": "İskenderun", "country": "Turkey", "latitude": 36.5875, "longitude": 36.1703, "timezone": "Europe/Istanbul", "county": "Hatay", "city": "Hatay"},
    {"name": "Dörtyol", "country": "Turkey", "latitude": 36.85, "longitude": 36.2167, "timezone": "Europe/Istanbul", "county": "Hatay", "city": "Hatay"},
    {"name": "Kırıkhan", "country": "Turkey", "latitude": 36.8333, "longitude": 36.4833, "timezone": "Europe/Istanbul", "county": "Hatay", "city": "Hatay"},
    {"name": "Reyhanlı", "country": "Turkey", "latitude": 36.2833, "longitude": 36.55, "timezone": "Europe/Istanbul", "county": "Hatay", "city": "Hatay"},
    {"name": "Samandağ", "country": "Turkey", "latitude": 36.0833, "longitude": 35.9833, "timezone": "Europe/Istanbul", "county": "Hatay", "city": "Hatay"},
    {"name": "Belen", "country": "Turkey", "latitude": 36.5, "longitude": 36.2, "timezone": "Europe/Istanbul", "county": "Hatay", "city": "Hatay"},
    {"name": "Erzin", "country": "Turkey", "latitude": 36.95, "longitude": 36.2, "timezone": "Europe/Istanbul", "county": "Hatay", "city": "Hatay"},
    {"name": "Yayladağı", "country": "Turkey", "latitude": 35.8833, "longitude": 36.0667, "timezone": "Europe/Istanbul", "county": "Hatay", "city": "Hatay"},
]

# Add all cities
data['cities'].extend(turkish_cities)

# Write back
with open('/Users/a195143/BitBucket/Compose/NamazVakitleri/prayer_settings/src/main/assets/cities.json', 'w') as f:
    json.dump(data, f, indent=2)

# Statistics
turkish = [c for c in data['cities'] if c['country'] == 'Turkey']
unique_names = set(c['name'] for c in turkish)
cities = set(c['city'] for c in turkish if 'city' in c)
counties = set(c['county'] for c in turkish if 'county' in c)

print(f"Total entries: {len(turkish)}")
print(f"Unique city names: {len(unique_names)}")
print(f"Unique cities (provinces): {len(cities)}")
print(f"Unique counties (districts): {len(counties)}")
