#!/usr/bin/env python3
"""Add nameTr/nameAr/nameFa fields for non-Turkey cities in cities.json."""
import json
import os

from localize_turkey_provinces import PROVINCES

CITIES_JSON = os.path.normpath(
    os.path.join(os.path.dirname(__file__), "..", "prayer_settings", "src", "main", "assets", "cities.json")
)

CITIES = {
    "Abha": {"tr": "Abha", "ar": "أبها", "fa": "ابها"},
    "Abu Dhabi": {"tr": "Abu Dabi", "ar": "أبو ظبي", "fa": "ابوظبی"},
    "Accra": {"tr": "Akra", "ar": "أكرا", "fa": "آکرا"},
    "Addis Ababa": {"tr": "Addis Ababa", "ar": "أديس أبابا", "fa": "آدیس آبابا"},
    "Agadir": {"tr": "Agadir", "ar": "أكادير", "fa": "اگادیر"},
    "Ahvaz": {"tr": "Ahvaz", "ar": "الأهواز", "fa": "اهواز"},
    "Al Ahmadi": {"tr": "El Ahmadi", "ar": "الأحمدي", "fa": "الاحمدی"},
    "Al Ain": {"tr": "El Ayn", "ar": "العين", "fa": "العین"},
    "Al Qunfudhah": {"tr": "El Kunfuze", "ar": "القنفذة", "fa": "قنفذه"},
    "Al Rayyan": {"tr": "Er Reyyan", "ar": "الريان", "fa": "الریان"},
    "Al-Baha": {"tr": "El Baha", "ar": "الباحة", "fa": "الباحه"},
    "Al-Jubail": {"tr": "El Cübeyl", "ar": "الجبيل", "fa": "جبیل"},
    "Al-Khobar": {"tr": "El Hubar", "ar": "الخبر", "fa": "خبر"},
    "Al-Madinah": {"tr": "Medine", "ar": "المدينة المنورة", "fa": "مدینه"},
    "Aleppo": {"tr": "Halep", "ar": "حلب", "fa": "حلب"},
    "Alexandria": {"tr": "İskenderiye", "ar": "الإسكندرية", "fa": "اسکندریه"},
    "Algiers": {"tr": "Cezayir", "ar": "الجزائر", "fa": "الجزیره"},
    "Amman": {"tr": "Amman", "ar": "عمّان", "fa": "امان"},
    "Amsterdam": {"tr": "Amsterdam", "ar": "أمستردام", "fa": "آمستردام"},
    "Annaba": {"tr": "Annabe", "ar": "عنابة", "fa": "عنابه"},
    "Antananarivo": {"tr": "Antananarivo", "ar": "أنتاناناريفو", "fa": "آنتاناناریوو"},
    "Aqaba": {"tr": "Akabe", "ar": "العقبة", "fa": "عقبه"},
    "Arar": {"tr": "Arar", "ar": "عرعر", "fa": "عرعر"},
    "Athens": {"tr": "Atina", "ar": "أثينا", "fa": "آتن"},
    "Baghdad": {"tr": "Bağdat", "ar": "بغداد", "fa": "بغداد"},
    "Bahawalpur": {"tr": "Bahavalpur", "ar": "بهاولبور", "fa": "بهاولپور"},
    "Bandung": {"tr": "Bandung", "ar": "باندونغ", "fa": "باندونگ"},
    "Bangalore": {"tr": "Bangalore", "ar": "بنغالور", "fa": "بنگلور"},
    "Bangkok": {"tr": "Bangkok", "ar": "بانكوك", "fa": "بانکوک"},
    "Barcelona": {"tr": "Barselona", "ar": "برشلونة", "fa": "بارسلونا"},
    "Basra": {"tr": "Basra", "ar": "البصرة", "fa": "بصره"},
    "Beijing": {"tr": "Pekin", "ar": "بكين", "fa": "پکن"},
    "Beirut": {"tr": "Beyrut", "ar": "بيروت", "fa": "بیروت"},
    "Benghazi": {"tr": "Bingazi", "ar": "بنغازي", "fa": "بنغازی"},
    "Berlin": {"tr": "Berlin", "ar": "برلين", "fa": "برلین"},
    "Birmingham": {"tr": "Birmingham", "ar": "برمنغهام", "fa": "بیرمنگام"},
    "Biskra": {"tr": "Biskra", "ar": "بسكرة", "fa": "بسکره"},
    "Brisbane": {"tr": "Brisbane", "ar": "بريزبن", "fa": "بریزبن"},
    "Brussels": {"tr": "Brüksel", "ar": "بروكسل", "fa": "بروکسل"},
    "Bucharest": {"tr": "Bükreş", "ar": "بوخارست", "fa": "بخارست"},
    "Budapest": {"tr": "Budapeşte", "ar": "بودابست", "fa": "بوداپست"},
    "Buraydah": {"tr": "Bureyde", "ar": "بريدة", "fa": "بریده"},
    "Busan": {"tr": "Busan", "ar": "بوسان", "fa": "بوسان"},
    "Cairo": {"tr": "Kahire", "ar": "القاهرة", "fa": "قاهره"},
    "Cape Town": {"tr": "Cape Town", "ar": "كيب تاون", "fa": "کیپتاون"},
    "Casablanca": {"tr": "Kazablanka", "ar": "الدار البيضاء", "fa": "کازابلانکا"},
    "Chengdu": {"tr": "Çengdu", "ar": "تشنغدو", "fa": "چنگدو"},
    "Chennai": {"tr": "Chennai", "ar": "تشيناي", "fa": "چنای"},
    "Chicago": {"tr": "Şikago", "ar": "شيكاغو", "fa": "شیکاگو"},
    "Chittagong": {"tr": "Çitagong", "ar": "شيتاغونغ", "fa": "چیتاگونگ"},
    "Colombo": {"tr": "Kolombo", "ar": "كولومبو", "fa": "کلمبو"},
    "Constantine": {"tr": "Konstantin", "ar": "قسنطينة", "fa": "قسنطینه"},
    "Copenhagen": {"tr": "Kopenhag", "ar": "كوبنهاغن", "fa": "کپنهاگ"},
    "Damascus": {"tr": "Şam", "ar": "دمشق", "fa": "دمشق"},
    "Dammam": {"tr": "Dammam", "ar": "الدمام", "fa": "دمام"},
    "Dar es Salaam": {"tr": "Darüsselam", "ar": "دار السلام", "fa": "دارالسلام"},
    "Delhi": {"tr": "Delhi", "ar": "دلهي", "fa": "دهلی"},
    "Depok": {"tr": "Depok", "ar": "ديبوك", "fa": "دپوک"},
    "Dhahran": {"tr": "Zahran", "ar": "الظهران", "fa": "ظهران"},
    "Dhaka": {"tr": "Dakka", "ar": "دكا", "fa": "داکا"},
    "Doha": {"tr": "Doha", "ar": "الدوحة", "fa": "دوحه"},
    "Dubai": {"tr": "Dubai", "ar": "دبي", "fa": "دبی"},
    "Dublin": {"tr": "Dublin", "ar": "دبلن", "fa": "دوبلین"},
    "Durban": {"tr": "Durban", "ar": "ديربان", "fa": "دوربان"},
    "Erbil": {"tr": "Erbil", "ar": "أربيل", "fa": "اربیل"},
    "Faisalabad": {"tr": "Faysalabad", "ar": "فيصل آباد", "fa": "فیصلآباد"},
    "Faiyum": {"tr": "Feyyum", "ar": "الفيوم", "fa": "فیوم"},
    "Fes": {"tr": "Fes", "ar": "فاس", "fa": "فاس"},
    "Frankfurt": {"tr": "Frankfurt", "ar": "فرانكفورت", "fa": "فرانکفورت"},
    "Geneva": {"tr": "Cenevre", "ar": "جنيف", "fa": "ژنو"},
    "Ghardaia": {"tr": "Gardaya", "ar": "غرداية", "fa": "غردایه"},
    "Giza": {"tr": "Gize", "ar": "الجيزة", "fa": "جیزه"},
    "Guangzhou": {"tr": "Guangzhou", "ar": "غوانزو", "fa": "گوانگژو"},
    "Gujranwala": {"tr": "Gucranvala", "ar": "غوجرانوالا", "fa": "گوجرانواله"},
    "Hafar Al-Batin": {"tr": "Hafar El Batin", "ar": "حفر الباطن", "fa": "حفر الباطن"},
    "Hail": {"tr": "Hail", "ar": "حائل", "fa": "حائل"},
    "Hama": {"tr": "Hama", "ar": "حماة", "fa": "حماه"},
    "Hamburg": {"tr": "Hamburg", "ar": "هامبورغ", "fa": "هامبورگ"},
    "Hanoi": {"tr": "Hanoi", "ar": "هانوي", "fa": "هانوی"},
    "Helsinki": {"tr": "Helsinki", "ar": "هلسنكي", "fa": "هلسینکی"},
    "Ho Chi Minh City": {"tr": "Ho Chi Minh Kenti", "ar": "مدينة هو تشي منه", "fa": "هوشیمین"},
    "Homs": {"tr": "Humus", "ar": "حمص", "fa": "حمص"},
    "Hong Kong": {"tr": "Hong Kong", "ar": "هونغ كونغ", "fa": "هنگ کنگ"},
    "Houston": {"tr": "Houston", "ar": "هيوستن", "fa": "هیوستون"},
    "Hyderabad": {"tr": "Haydarabad", "ar": "حيدر آباد", "fa": "حیدرآباد"},
    "Ipoh": {"tr": "Ipoh", "ar": "إيبوه", "fa": "ایپوه"},
    "Irbid": {"tr": "İrbid", "ar": "إربد", "fa": "اربد"},
    "Isfahan": {"tr": "İsfahan", "ar": "أصفهان", "fa": "اصفهان"},
    "Ismailia": {"tr": "İsmailiye", "ar": "الإسماعيلية", "fa": "اسماعیلیه"},
    "Jakarta": {"tr": "Cakarta", "ar": "جاكرتا", "fa": "جاکارتا"},
    "Jeddah": {"tr": "Cidde", "ar": "جدة", "fa": "جده"},
    "Jizan": {"tr": "Cizan", "ar": "جازان", "fa": "جازان"},
    "Johannesburg": {"tr": "Johannesburg", "ar": "جوهانسبرغ", "fa": "ژوهانسبورگ"},
    "Johor Bahru": {"tr": "Johor Bahru", "ar": "جوهر بهرو", "fa": "جوهور بهرو"},
    "Jouf": {"tr": "El Cevf", "ar": "الجوف", "fa": "جوف"},
    "Kairouan": {"tr": "Kayrevan", "ar": "القيروان", "fa": "قیروان"},
    "Kampala": {"tr": "Kampala", "ar": "كمبالا", "fa": "کامپالا"},
    "Kano": {"tr": "Kano", "ar": "كانو", "fa": "کانو"},
    "Karachi": {"tr": "Karaçi", "ar": "كراتشي", "fa": "کراچی"},
    "Karaj": {"tr": "Kerec", "ar": "كرج", "fa": "کرج"},
    "Karbala": {"tr": "Kerbela", "ar": "كربلاء", "fa": "کربلا"},
    "Kathmandu": {"tr": "Katmandu", "ar": "كاتماندو", "fa": "کاتماندو"},
    "Kazan": {"tr": "Kazan", "ar": "قازان", "fa": "قازان"},
    "Kermanshah": {"tr": "Kirmanşah", "ar": "كرمانشاه", "fa": "کرمانشاه"},
    "Khamis Mushait": {"tr": "Hamis Muşayt", "ar": "خميس مشيط", "fa": "خمیس مشیط"},
    "Khartoum": {"tr": "Hartum", "ar": "الخرطوم", "fa": "خارطوم"},
    "Kolkata": {"tr": "Kalküta", "ar": "كلكتا", "fa": "کلکته"},
    "Kota Bharu": {"tr": "Kota Bharu", "ar": "كوتا بهارو", "fa": "کوتا بهارو"},
    "Krakow": {"tr": "Kraków", "ar": "كراكوف", "fa": "کراکوف"},
    "Kuala Lumpur": {"tr": "Kuala Lumpur", "ar": "كوالالمبور", "fa": "کوالالامپور"},
    "Kuala Terengganu": {"tr": "Kuala Terengganu", "ar": "كوالا ترغكانو", "fa": "کوالا ترنگانو"},
    "Kudus": {"tr": "Kudus", "ar": "قدس", "fa": "کودوس"},
    "Kuwait City": {"tr": "Kuveyt Şehri", "ar": "مدينة الكويت", "fa": "کویت"},
    "Kyoto": {"tr": "Kyoto", "ar": "كيوتو", "fa": "کیوتو"},
    "Lagos": {"tr": "Lagos", "ar": "لاغوس", "fa": "لاگوس"},
    "Lahore": {"tr": "Lahor", "ar": "لاهور", "fa": "لاهور"},
    "Latakia": {"tr": "Lazkiye", "ar": "اللاذقية", "fa": "لاذقیه"},
    "Lisbon": {"tr": "Lizbon", "ar": "لشبونة", "fa": "لیسبون"},
    "London": {"tr": "Londra", "ar": "لندن", "fa": "لندن"},
    "Los Angeles": {"tr": "Los Angeles", "ar": "لوس أنجلوس", "fa": "لسآنجلس"},
    "Luxor": {"tr": "Luksor", "ar": "الأقصر", "fa": "اقصر"},
    "Lyon": {"tr": "Lyon", "ar": "ليون", "fa": "لیون"},
    "Madrid": {"tr": "Madrid", "ar": "مدريد", "fa": "مادرید"},
    "Makassar": {"tr": "Makassar", "ar": "ماكاسار", "fa": "ماکاسار"},
    "Manama": {"tr": "Manama", "ar": "المنامة", "fa": "منامه"},
    "Manchester": {"tr": "Manchester", "ar": "مانشستر", "fa": "منچستر"},
    "Manila": {"tr": "Manila", "ar": "مانيلا", "fa": "مانیل"},
    "Mansoura": {"tr": "Mansure", "ar": "المنصورة", "fa": "منصوره"},
    "Marrakech": {"tr": "Marakeş", "ar": "مراكش", "fa": "مراکش"},
    "Marseille": {"tr": "Marsilya", "ar": "مارسيليا", "fa": "مارسی"},
    "Mashhad": {"tr": "Meşhed", "ar": "مشهد", "fa": "مشهد"},
    "Medan": {"tr": "Medan", "ar": "ميدان", "fa": "مدان"},
    "Medine": {"tr": "Medine", "ar": "المدينة", "fa": "مدینه"},
    "Mekka": {"tr": "Mekke", "ar": "مكة المكرمة", "fa": "مکه"},
    "Melbourne": {"tr": "Melbourne", "ar": "ملبورن", "fa": "ملبورن"},
    "Milan": {"tr": "Milano", "ar": "ميلانو", "fa": "میلان"},
    "Mogadishu": {"tr": "Mogadişu", "ar": "مقديشو", "fa": "موگادیشو"},
    "Montreal": {"tr": "Montreal", "ar": "مونتريال", "fa": "مونترآل"},
    "Moscow": {"tr": "Moskova", "ar": "موسكو", "fa": "مسکو"},
    "Mosul": {"tr": "Musul", "ar": "الموصل", "fa": "موصل"},
    "Muharraq": {"tr": "Muharrak", "ar": "المحرق", "fa": "محرق"},
    "Multan": {"tr": "Multan", "ar": "ملتان", "fa": "مولتان"},
    "Mumbai": {"tr": "Mumbai", "ar": "مومباي", "fa": "بمبئی"},
    "Munich": {"tr": "Münih", "ar": "ميونخ", "fa": "مونیخ"},
    "Muscat": {"tr": "Maskat", "ar": "مسقط", "fa": "مسقط"},
    "Nairobi": {"tr": "Nairobi", "ar": "نيروبي", "fa": "نایروبی"},
    "Najaf": {"tr": "Necef", "ar": "النجف", "fa": "نجف"},
    "Najran": {"tr": "Necran", "ar": "نجران", "fa": "نجران"},
    "Nanjing": {"tr": "Nankin", "ar": "نانجينغ", "fa": "نانجینگ"},
    "New York": {"tr": "New York", "ar": "نيويورك", "fa": "نیویورک"},
    "Novosibirsk": {"tr": "Novosibirsk", "ar": "نوفوسيبيرسك", "fa": "نووسیبیرسک"},
    "Oran": {"tr": "Vahran", "ar": "وهران", "fa": "وهران"},
    "Osaka": {"tr": "Osaka", "ar": "أوساكا", "fa": "اوساکا"},
    "Oslo": {"tr": "Oslo", "ar": "أوسلو", "fa": "اسلو"},
    "Ouargla": {"tr": "Vargla", "ar": "ورقلة", "fa": "ورقله"},
    "Palembang": {"tr": "Palembang", "ar": "باليمبانغ", "fa": "پالمبانگ"},
    "Paris": {"tr": "Paris", "ar": "باريس", "fa": "پاریس"},
    "Penang": {"tr": "Penang", "ar": "بينانغ", "fa": "پنانگ"},
    "Perth": {"tr": "Perth", "ar": "بيرث", "fa": "پرت"},
    "Peshawar": {"tr": "Peşaver", "ar": "بيشاور", "fa": "پیشاور"},
    "Phnom Penh": {"tr": "Phnom Penh", "ar": "بنوم بنه", "fa": "پنومپن"},
    "Phoenix": {"tr": "Phoenix", "ar": "فينيكس", "fa": "فینیکس"},
    "Porto": {"tr": "Porto", "ar": "بورتو", "fa": "پورتو"},
    "Prague": {"tr": "Prag", "ar": "براغ", "fa": "پراگ"},
    "Qassim": {"tr": "El Kasim", "ar": "القصيم", "fa": "قصیم"},
    "Qom": {"tr": "Kum", "ar": "قم", "fa": "قم"},
    "Rabat": {"tr": "Rabat", "ar": "الرباط", "fa": "رباط"},
    "Rawalpindi": {"tr": "Ravalpindi", "ar": "روالبندي", "fa": "راولپندی"},
    "Riffa": {"tr": "Rifa", "ar": "الرفاع", "fa": "رفاع"},
    "Riyadh": {"tr": "Riyad", "ar": "الرياض", "fa": "ریاض"},
    "Rome": {"tr": "Roma", "ar": "روما", "fa": "رم"},
    "Rotterdam": {"tr": "Rotterdam", "ar": "روتردام", "fa": "روتردام"},
    "Saint Petersburg": {"tr": "Sankt-Peterburg", "ar": "سانت بطرسبرغ", "fa": "سنپترزبورگ"},
    "Salalah": {"tr": "Salale", "ar": "صلالة", "fa": "صلاله"},
    "Sargodha": {"tr": "Sargodha", "ar": "سرغودها", "fa": "سرگودها"},
    "Semarang": {"tr": "Semarang", "ar": "سمارانغ", "fa": "سمارانگ"},
    "Seoul": {"tr": "Seul", "ar": "سيول", "fa": "سئول"},
    "Sfax": {"tr": "Safaks", "ar": "صفاقس", "fa": "صفاقس"},
    "Shanghai": {"tr": "Şanghay", "ar": "شنغهاي", "fa": "شانگهای"},
    "Sharjah": {"tr": "Şarika", "ar": "الشارقة", "fa": "شارجه"},
    "Shenzhen": {"tr": "Şenzen", "ar": "شنتشن", "fa": "شنژن"},
    "Shiraz": {"tr": "Şiraz", "ar": "شيراز", "fa": "شیراز"},
    "Sialkot": {"tr": "Siyalkot", "ar": "سيالكوت", "fa": "سیالکوت"},
    "Sidon": {"tr": "Sayda", "ar": "صيدا", "fa": "صیدا"},
    "Singapore": {"tr": "Singapur", "ar": "سنغافورة", "fa": "سنگاپور"},
    "Sohar": {"tr": "Suhar", "ar": "صحار", "fa": "صحار"},
    "Sousse": {"tr": "Susa", "ar": "سوسة", "fa": "سوسه"},
    "Stockholm": {"tr": "Stockholm", "ar": "ستوكهولم", "fa": "استکهلم"},
    "Suez": {"tr": "Süveyş", "ar": "السويس", "fa": "سوئز"},
    "Surabaya": {"tr": "Surabaya", "ar": "سورابايا", "fa": "سورابایا"},
    "Sydney": {"tr": "Sidney", "ar": "سيدني", "fa": "سیدنی"},
    "Tabriz": {"tr": "Tebriz", "ar": "تبريز", "fa": "تبریز"},
    "Tabuk": {"tr": "Tebük", "ar": "تبوك", "fa": "تبوک"},
    "Taif": {"tr": "Taif", "ar": "الطائف", "fa": "طائف"},
    "Taipei": {"tr": "Taipei", "ar": "تايبيه", "fa": "تایپه"},
    "Tangerang": {"tr": "Tangerang", "ar": "تانغيرانغ", "fa": "تانگرانگ"},
    "Tangier": {"tr": "Tanca", "ar": "طنجة", "fa": "طنجه"},
    "Tanta": {"tr": "Tanta", "ar": "طنطا", "fa": "طنطا"},
    "Tehran": {"tr": "Tahran", "ar": "طهران", "fa": "تهران"},
    "Thessaloniki": {"tr": "Selanik", "ar": "سالونيك", "fa": "سالونیک"},
    "Tokyo": {"tr": "Tokyo", "ar": "طوكيو", "fa": "توکیو"},
    "Toronto": {"tr": "Toronto", "ar": "تورونتو", "fa": "تورنتو"},
    "Tripoli": {"tr": "Trablus", "ar": "طرابلس", "fa": "طرابلس"},
    "Tunis": {"tr": "Tunus", "ar": "تونس", "fa": "تونس"},
    "Vancouver": {"tr": "Vancouver", "ar": "فانكوفر", "fa": "ونکوور"},
    "Vienna": {"tr": "Viyana", "ar": "فيينا", "fa": "وین"},
    "Warsaw": {"tr": "Varşova", "ar": "وارسو", "fa": "ورشو"},
    "Wuhan": {"tr": "Vuhan", "ar": "ووهان", "fa": "ووهان"},
    "Xian": {"tr": "Şian", "ar": "شيان", "fa": "شیان"},
    "Yanbu": {"tr": "Yenbu", "ar": "ينبع", "fa": "ینبع"},
    "Yekaterinburg": {"tr": "Yekaterinburg", "ar": "يكاترينبورغ", "fa": "یکاترینبورگ"},
    "Zagazig": {"tr": "Zekazik", "ar": "الزقازيق", "fa": "زقازیق"},
    "Zarqa": {"tr": "Zerka", "ar": "الزرقاء", "fa": "زرقاء"},
    "Zurich": {"tr": "Zürih", "ar": "زيورخ", "fa": "زوریخ"},
}

def main():
    with open(CITIES_JSON, encoding="utf-8") as f:
        data = json.load(f)
    updated = 0
    for city in data["cities"]:
        name = city["name"]
        name_trans = CITIES.get(name)
        if name_trans is None and city["country"] == "Turkey":
            name_trans = PROVINCES.get(name)
        if name_trans:
            for lang, value in name_trans.items():
                city[f"name{lang.capitalize()}"] = value
            updated += 1
    with open(CITIES_JSON, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print(f"Localized city names for {updated} cities")

if __name__ == "__main__":
    main()
